@baseUrl = http://localhost:3000/articles

### POST Article 테스트
POST {{baseUrl}}
Content-Type: application/json

{
    "title": "잠자고 싶다",
    "content": "나는야 잠꾸러기",
    "userId": 3
}

POST {{baseUrl}}
Content-Type: application/json

{
    "title": "오리사 궁극기 낙사",
    "content": "일리오스 우물에서 당했는데 분하지도 않고 그냥 신기하기만 했음",
    "userId": 2
}

### GET Article 테스트
GET {{baseUrl}}/1
GET {{baseUrl}}/7

### GET Article List 테스트
GET {{baseUrl}}
GET {{baseUrl}}?orderBy=createdAt
GET {{baseUrl}}?orderBy=createdAt&pageSize=2&page=1
GET {{baseUrl}}?orderBy=createdAt&pageSize=2&page=2
GET {{baseUrl}}?orderBy=createdAt&pageSize=2&page=1&keyword=오늘
GET {{baseUrl}}?orderBy=favoriteCount
GET {{baseUrl}}?orderBy=favoriteCount&pageSize=2&page=1
GET {{baseUrl}}?orderBy=favoriteCount&pageSize=2&page=1&keyword=오늘

### GET Best 3
GET {{baseUrl}}?orderBy=favoriteCount&pageSize=3&page=1 

### PATCH Article 테스트
PATCH {{baseUrl}}/14
Content-Type: application/json

{
    "title": "얼렁 끝내야하는데!!!!!",
    "content": "잠오고 바쁘네 큰일이다"
}

PATCH {{baseUrl}}/1
Content-Type: application/json

{
    "title": "일리오스 오리사 궁극기 낙사"
}

### DELETE Article 테스트
DELETE {{baseUrl}}/12
