@baseUrl = http://localhost:3000/articles

### POST Article 테스트
POST {{baseUrl}}
Content-Type: application/json

{
    "title": "본가 내려왔어요",
    "content": "배불리 맛있는거 많이 먹는중 희희",
    "userId": 1
}

POST {{baseUrl}}
Content-Type: application/json

{
    "title": "오리사 궁극기 낙사",
    "content": "일리오스 우물에서 당했는데 분하지도 않고 그냥 신기하기만 했음",
    "userId": 2
}

### GET Article 테스트
GET {{baseUrl}}/1
GET {{baseUrl}}/2


### GET Best 3 Article 테스트
GET {{baseUrl}}/best

### GET Article List 테스트
GET {{baseUrl}}
GET {{baseUrl}}?orderBy=createdAt
GET {{baseUrl}}?orderBy=createdAt&pageSize=2&page=1
GET {{baseUrl}}?orderBy=createdAt&pageSize=2&page=2
GET {{baseUrl}}?orderBy=createdAt&pageSize=2&page=1&keyword=오늘
GET {{baseUrl}}?orderBy=favoriteCount
GET {{baseUrl}}?orderBy=favoriteCount&pageSize=2&page=1
GET {{baseUrl}}?orderBy=favoriteCount&pageSize=2&page=1&keyword=오늘

### GET Best 3
GET {{baseUrl}}?orderBy=favoriteCount&pageSize=3&page=1 

### PATCH Article 테스트
PATCH {{baseUrl}}/1
Content-Type: application/json

{
    "title": "일리오스 궁극기 낙사 당함",
    "content": "일리오스 우물에서 우리 팀 셋이서 당했는데 분하지도 않고 그냥 신기해서 전챗으로 인정 날렸음"
}

PATCH {{baseUrl}}/1
Content-Type: application/json

{
    "title": "일리오스 오리사 궁극기 낙사"
}

### DELETE Article 테스트
DELETE {{baseUrl}}/8
