@baseUrl = http://localhost:3000/articles

### POST Article 테스트
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDYzNTQsImV4cCI6MTc4MzE0OTk1NH0.nx5QWehbrpVSudjQHSM9iAa2kH2QqjMJAxkbr06-qwo

{
    "title": "똥",
    "content": "바나나 똥"
}

POST {{baseUrl}}
Content-Type: application/json

{
    "title": "오리사 궁극기 낙사",
    "content": "일리오스 우물에서 당했는데 분하지도 않고 그냥 신기하기만 했음"
}

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDYzNTQsImV4cCI6MTc4MzE0OTk1NH0.nx5QWehbrpVSudjQHSM9iAa2kH2QqjMJAxkbr06-qwo

{
    "title": "",
    "content": "일리오스 우물에서 당했는데 분하지도 않고 그냥 신기하기만 했음"
}

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDYzNTQsImV4cCI6MTc4MzE0OTk1NH0.nx5QWehbrpVSudjQHSM9iAa2kH2QqjMJAxkbr06-qwo

{
    "title": "오리사 궁극기 낙사",
    "content": ""
}

### GET Article 테스트
GET {{baseUrl}}/1
GET {{baseUrl}}/200

### GET Article List 테스트
GET {{baseUrl}}
GET {{baseUrl}}?orderBy=createdAt
GET {{baseUrl}}?orderBy=createdAt&pageSize=2&page=1
GET {{baseUrl}}?orderBy=createdAt&pageSize=2&page=2
GET {{baseUrl}}?orderBy=createdAt&pageSize=2&page=1&keyword=오늘
GET {{baseUrl}}?orderBy=favoriteCount
GET {{baseUrl}}?orderBy=favoriteCount&pageSize=2&page=1
GET {{baseUrl}}?orderBy=favoriteCount&pageSize=2&page=1&keyword=오늘

GET {{baseUrl}}?orderBy=createdAt&pageSize=0&page=1&keyword=오늘
GET {{baseUrl}}?orderBy=createdAt&pageSize=2&page=-1&keyword=오늘
GET {{baseUrl}}?orderBy=whatever&pageSize=2&page=1&keyword=오늘

### GET Best 3
GET {{baseUrl}}?orderBy=favoriteCount&pageSize=3&page=1 

### PATCH Article 테스트
PATCH {{baseUrl}}/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDYzNTQsImV4cCI6MTc4MzE0OTk1NH0.nx5QWehbrpVSudjQHSM9iAa2kH2QqjMJAxkbr06-qwo

{
    "title": "사실 나도 옵치 하지롱",
    "content": "옵옵옵"
}

PATCH {{baseUrl}}/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDYzNTQsImV4cCI6MTc4MzE0OTk1NH0.nx5QWehbrpVSudjQHSM9iAa2kH2QqjMJAxkbr06-qwo

{
    "content": "오버워치가 제일좋아"
}

PATCH {{baseUrl}}/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDYzNTQsImV4cCI6MTc4MzE0OTk1NH0.nx5QWehbrpVSudjQHSM9iAa2kH2QqjMJAxkbr06-qwo

{
    "title": "사실 마크 말도고 옵치도 하지롱"
}

PATCH {{baseUrl}}/17
Content-Type: application/json

{
    "title": "사실 나도 옵치 하지롱",
    "content": "옵옵옵"
}

PATCH {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDYzNTQsImV4cCI6MTc4MzE0OTk1NH0.nx5QWehbrpVSudjQHSM9iAa2kH2QqjMJAxkbr06-qwo

{
    "title": "사실 나도 옵치 하지롱",
    "content": "옵옵옵"
}

PATCH {{baseUrl}}/100
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDYzNTQsImV4cCI6MTc4MzE0OTk1NH0.nx5QWehbrpVSudjQHSM9iAa2kH2QqjMJAxkbr06-qwo

{
    "content": "우씨 언제 끝나"
}

PATCH {{baseUrl}}/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDYzNTQsImV4cCI6MTc4MzE0OTk1NH0.nx5QWehbrpVSudjQHSM9iAa2kH2QqjMJAxkbr06-qwo

{
    "title":"",
    "content": ""
}

PATCH {{baseUrl}}/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDYzNTQsImV4cCI6MTc4MzE0OTk1NH0.nx5QWehbrpVSudjQHSM9iAa2kH2QqjMJAxkbr06-qwo

{

}

### DELETE Article 테스트
DELETE {{baseUrl}}/18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDYzNTQsImV4cCI6MTc4MzE0OTk1NH0.nx5QWehbrpVSudjQHSM9iAa2kH2QqjMJAxkbr06-qwo

DELETE {{baseUrl}}/18

DELETE {{baseUrl}}/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDYzNTQsImV4cCI6MTc4MzE0OTk1NH0.nx5QWehbrpVSudjQHSM9iAa2kH2QqjMJAxkbr06-qwo

## Like Article 테스트
POST {{baseUrl}}/1/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMyNDcxNjcsImV4cCI6MTc4MzI1MDc2N30.JBhzaBL3Gy2JfOfI4YrSVJ5LOXrHT4BFyVCk9J9Md4c

DELETE {{baseUrl}}/1/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMyNDcxNjcsImV4cCI6MTc4MzI1MDc2N30.JBhzaBL3Gy2JfOfI4YrSVJ5LOXrHT4BFyVCk9J9Md4c