@baseUrl = http://localhost:3000/articles/1/comments

### POST Comment 테스트
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODY0MzYwNjYsImV4cCI6MTc4NjQzOTY2Nn0.frLRIulIRN6f3RhXlOobtYSr5j5uD-jSx4Odag1U-eg

{
    "content": "근데 이거 무슨 글이었더라"
}

POST {{baseUrl}}
Content-Type: application/json

{
    "content": "오 해볼게요 입문으로 좋은 캐 뭐가 있나요?"
}

POST http://localhost:3000/articles/1000/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODY0MzYwNjYsImV4cCI6MTc4NjQzOTY2Nn0.frLRIulIRN6f3RhXlOobtYSr5j5uD-jSx4Odag1U-eg

{
    "content": "똥탱"
}

POST http://localhost:3000/articles/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODY0MzYwNjYsImV4cCI6MTc4NjQzOTY2Nn0.frLRIulIRN6f3RhXlOobtYSr5j5uD-jSx4Odag1U-eg

{
    "content": ""
}


### GET Comment 테스트
GET {{baseUrl}}
GET http://localhost:3000/articles/10000/comments
GET {{baseUrl}}?cursor=1

### PATCH Article 테스트
PATCH {{baseUrl}}/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODY0MzYwNjYsImV4cCI6MTc4NjQzOTY2Nn0.frLRIulIRN6f3RhXlOobtYSr5j5uD-jSx4Odag1U-eg

{
    "content": "뜬금없지만 마크로 돈 벌어요 저는"
}

PATCH {{baseUrl}}/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDUxMjgsImV4cCI6MTc4MzE0ODcyOH0.O-Wec5v5lEriOGQFvDyfO-16LNm6lMuDwCO_MAE9PMk

{
    "content": "오버워치지~!!!!!!!!!!!"
}

PATCH {{baseUrl}}/2
Content-Type: application/json

{
    "content": "오버워치지~!!!!!!!!!!!"
}

PATCH {{baseUrl}}/4000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODY0MzYwNjYsImV4cCI6MTc4NjQzOTY2Nn0.frLRIulIRN6f3RhXlOobtYSr5j5uD-jSx4Odag1U-eg

{
    "content": "오버워치지~!!!!!!!!!!!"
}

PATCH http://localhost:3000/articles/5/comments/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDUxMjgsImV4cCI6MTc4MzE0ODcyOH0.O-Wec5v5lEriOGQFvDyfO-16LNm6lMuDwCO_MAE9PMk

{
    "content": "오버워치지~!!!!!!!!!!!"
}

PATCH http://localhost:3000/articles/1000/comments/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDUxMjgsImV4cCI6MTc4MzE0ODcyOH0.O-Wec5v5lEriOGQFvDyfO-16LNm6lMuDwCO_MAE9PMk

{
    "content": "오버워치지~!!!!!!!!!!!"
}

### DELETE Comment 테스트
DELETE {{baseUrl}}/32
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODY0MzYwNjYsImV4cCI6MTc4NjQzOTY2Nn0.frLRIulIRN6f3RhXlOobtYSr5j5uD-jSx4Odag1U-eg

DELETE {{baseUrl}}/12

DELETE {{baseUrl}}/1200
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDUxMjgsImV4cCI6MTc4MzE0ODcyOH0.O-Wec5v5lEriOGQFvDyfO-16LNm6lMuDwCO_MAE9PMk

DELETE http://localhost:3000/articles/3/comments/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDUxMjgsImV4cCI6MTc4MzE0ODcyOH0.O-Wec5v5lEriOGQFvDyfO-16LNm6lMuDwCO_MAE9PMk

DELETE http://localhost:3000/articles/1000/comments/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDUxMjgsImV4cCI6MTc4MzE0ODcyOH0.O-Wec5v5lEriOGQFvDyfO-16LNm6lMuDwCO_MAE9PMk
