@baseUrl = http://localhost:3000/products

### GET Product 테스트
GET {{baseUrl}}

GET {{baseUrl}}?orderBy=favorite

GET {{baseUrl}}?orderBy=favorite&pageSize=2&page=1

GET {{baseUrl}}?orderBy=favorite&pageSize=2&page=2

GET {{baseUrl}}?orderBy=favorite&pageSize=2&page=1&keyword=브

GET {{baseUrl}}?orderBy=favorite&pageSize=2&page=1&keyword=힐

GET {{baseUrl}}?orderBy=whatever&pageSize=2&page=1
GET {{baseUrl}}?orderBy=favorite&pageSize=0&page=1
GET {{baseUrl}}?orderBy=favorite&pageSize=2&page=0

GET {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwNjQyMTksImV4cCI6MTc4NzA2NzgxOX0.W6nRJuxmN0iuZtx55_I5ZtruVMuiiPAC4CzNIwdORBE

### GET Product Detail 테스트
GET {{baseUrl}}/1

GET {{baseUrl}}/2000

GET {{baseUrl}}/21
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwNjQyMTksImV4cCI6MTc4NzA2NzgxOX0.W6nRJuxmN0iuZtx55_I5ZtruVMuiiPAC4CzNIwdORBE

### POST Product 테스트
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwNjQyMTksImV4cCI6MTc4NzA2NzgxOX0.W6nRJuxmN0iuZtx55_I5ZtruVMuiiPAC4CzNIwdORBE

{
  "name": "디몬의 부스터",
  "description": "표지사기이다. 애니메이션에서는 상하좌우로 움직이더니 결론적으로는 못 나는 메카가 출품됐다.",
  "tags": ["탱커", "표지사기"],
  "price": 500
}

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDExMDcsImV4cCI6MTc4MzE0NDcwN30.aCARFDuoyzQ9EOZsS_Cdsv2hFnMExOTkFe0b9r7GjnU

{
  "name": "에코의 관",
  "description": "에코가 갇혀있던 관이다. 캐서디가 열었다.",
  "tags": ["상자"],
  "price": 45000
}

POST {{baseUrl}}
Content-Type: application/json

{
  "name": "에코의 관",
  "description": "에코가 갇혀있던 관이다. 캐서디가 열었다.",
  "tags": ["상자"],
  "price": 45000
}

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwNjQyMTksImV4cCI6MTc4NzA2NzgxOX0.W6nRJuxmN0iuZtx55_I5ZtruVMuiiPAC4CzNIwdORBE

{
  "name": "",
  "description": "에코가 갇혀있던 관이다. 캐서디가 열었다.",
  "tags": ["상자"],
  "price": 45000
}

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwNjQyMTksImV4cCI6MTc4NzA2NzgxOX0.W6nRJuxmN0iuZtx55_I5ZtruVMuiiPAC4CzNIwdORBE

{
  "name": "에코의 관",
  "description": "",
  "tags": ["상자"],
  "price": 45000
}

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwNjQyMTksImV4cCI6MTc4NzA2NzgxOX0.W6nRJuxmN0iuZtx55_I5ZtruVMuiiPAC4CzNIwdORBE

{
  "name": "에코의 관",
  "description": "에코가 갇혀있던 관이다. 캐서디가 열었다.",
  "tags": ["상자"]
}

### PATCH Product 테스트
PATCH {{baseUrl}}/20
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODMxNDExMDcsImV4cCI6MTc4MzE0NDcwN30.aCARFDuoyzQ9EOZsS_Cdsv2hFnMExOTkFe0b9r7GjnU

{
  "name": "에코의 관",
  "description": "에코가 갇혀있던 관이다. 캐서디가 열었다. 배송사 Deadlock Co.",
  "tags": ["상자", "포근"],
  "price": 62950
}

PATCH {{baseUrl}}/1000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwNjQyMTksImV4cCI6MTc4NzA2NzgxOX0.W6nRJuxmN0iuZtx55_I5ZtruVMuiiPAC4CzNIwdORBE

{
  "name": "아나의 생체 슈류탄",
  "description": "정커퀸 궁이 스킬 한번으로 딸깍? 거기다가 힐증까지 된다고?",
  "tags": ["힐러", "싸가지", "개사기", "정커퀸궁"],
  "price": 62950
}

PATCH {{baseUrl}}/26
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwNjQyMTksImV4cCI6MTc4NzA2NzgxOX0.W6nRJuxmN0iuZtx55_I5ZtruVMuiiPAC4CzNIwdORBE

{
  "tags": ["뭥미"]
}

PATCH {{baseUrl}}/26
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwNjQyMTksImV4cCI6MTc4NzA2NzgxOX0.W6nRJuxmN0iuZtx55_I5ZtruVMuiiPAC4CzNIwdORBE

{
  "name": "",
  "description": ""
}

### DELETE Product 테스트
DELETE {{baseUrl}}/28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwNjQyMTksImV4cCI6MTc4NzA2NzgxOX0.W6nRJuxmN0iuZtx55_I5ZtruVMuiiPAC4CzNIwdORBE

## Like Product 테스트
POST {{baseUrl}}/29/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwNjQyMTksImV4cCI6MTc4NzA2NzgxOX0.W6nRJuxmN0iuZtx55_I5ZtruVMuiiPAC4CzNIwdORBE

DELETE {{baseUrl}}/29/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwNjQyMTksImV4cCI6MTc4NzA2NzgxOX0.W6nRJuxmN0iuZtx55_I5ZtruVMuiiPAC4CzNIwdORBE