@baseUrl=http://localhost:3000/user

GET {{baseUrl}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcxMDM1OTIsImV4cCI6MTc4NzEwNzE5Mn0.BzFNIoKnxWBqWHZPEVcEZcqgEbbUclVGNHYfWvoAxVU

GET {{baseUrl}}/me