@baseUrl=http://localhost:3000/user

GET {{baseUrl}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Iuygle2YleykgCIsImVtYWlsIjoicnVsbHVkaW5vQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnVsbHVkaW5vIiwiZGVsZXRlZEF0IjpudWxsLCJpYXQiOjE3ODcwOTg5ODgsImV4cCI6MTc4NzEwMjU4OH0.yHe5rUEmL3a5WZaiVI39c-NLL4EIMXow5bFNK0IRqXM

GET {{baseUrl}}/me