@baseUrl = https://one3-sprint-mission-be-owah.onrender.com

POST {{baseUrl}}/product
Content-Type: application/json

{
  "name": "김대영",
  "price": 10000000000000,
  "description": "이것은 테스트 설명 입니다. 하하하하하하",
  "tags": ["#4팀", "#화이팅", "#김대영"]
}