
@baseUrl = http://localhost:3000

### Article 테스트

POST {{baseUrl}}/articles
Content-Type: application/json

{
  "title": "3번째 게시글입니다.",
  "content": "3번째 content입니다.."
}

### 게시글 조회

GET {{baseUrl}}/articles

### 게시글 추가

POST {{baseUrl}}/articles
Content-Type: application/json

{
  "title": "과연 게시글이 최신일까?",
  "content": "처음 써보는 게시글입니다"
}

### 페이지 별 조회

GET {{baseUrl}}/articles/?page=1&limit=1

### 페이지 별 조회2

GET {{baseUrl}}/articles/?page=2&limit=1

### 페이지 별 조회3

GET {{baseUrl}}/articles/?page=1&limit=2

### 검색 조회

GET {{baseUrl}}/articles/?search=안녕



### 단건 조회

GET {{baseUrl}}/articles/1


### 게시글 수정
PATCH {{baseUrl}}/articles/1
Content-Type: application/json

{
  "title": "수정됩니다.",
  "content": "수정하였습니다."
}

### 게시글 삭제
DELETE {{baseUrl}}/articles/30


### Comment Test

### 댓글 등록
POST {{baseUrl}}/articles/1/comments
Content-Type: application/json

{
  "content": "댓글을 답니다."
}


### 댓글 수정
PATCH {{baseUrl}}/comments/10
Content-Type: application/json

{
  "content": "안녕하세요 판다마켓 거래합니다."
}

### 댓글 삭제
DELETE {{baseUrl}}/comments/1

### 댓글 조회 False일 때 실제 요청은 takeNum=3
GET {{baseUrl}}/articles/12/comments?take=2

### 댓글 조회 1개 떼어내고 1개만 응답
GET {{baseUrl}}/articles/12/comments?take=1

### 댓글 조회 cursor를 같이 보내는 다음 페이지 요청
GET {{baseUrl}}/articles/12/comments?take=1&cursor=2
