@localUrl = http://localhost:3000
@baseUrl = {{$processEnv process environment variable name}}


### 댓글 목록 조회
GET {{localUrl}}/articles/y94tpXHgiR8U-IeTTvHeP/comments


### 댓글 삭제
DELETE {{localUrl}}/articles/comments/kxr_PSTsxBYcrq6eh1imZ



### 댓글 등록
POST {{localUrl}}/articles/y94tpXHgiR8U-IeTTvHeP/comments
Content-Type: application/json

{
  "content": "이것은 내용입니다222만 무슨 문제라도?"
}

### 댓글 수정
PATCH  {{localUrl}}/articles/comments/rEfGGSmFX0yB1snUZvu08
Content-Type: application/json    

{
  "content" : "12312312412asedwdasfd12312123124"
}