@localUrl = http://localhost:3000


### 게시물 조회
GET {{localUrl}}/articles


### 게시물 목록 조회
GET {{localUrl}}/articles?keyword=Porro 


### 
GET  {{localUrl}}/articles/CeNq1k6-5oARIy9VAB5y0


### 게시글 삭제
DELETE {{localUrl}}/articles/8-6EP3BzYf6cc3gYIajgk

### 게시글 등록
POST {{localUrl}}/articles
Content-Type: application/json

{
  "title": "로된222 타이틀",
  "content": "이것은 내용입니다만 무슨 문제라도?"
}


### 게시글 수정
PATCH  {{localUrl}}/articles/CeNq1k6-5oARIy9VAB5y0
Content-Type: application/json    

{
  "title": "축구공3",
  "content": "419613198415626948516"
}