@baseUrl = https://one3-sprint-mission-be-owah.onrender.com
@localUrl = http://localhost:3000


###상품 조회
GET {{localUrl}}/product?keyword=닌텐도스위치




### 상품 목록 조회
GET {{localUrl}}/product


###
GET  {{localUrl}}/product/6AfDUUJ7J28rrCylzYrlq



### 상품 등록
POST {{localUrl}}/product
Content-Type: application/json

{
  "name": "축구공",
  "price": "300000",
  "description": "이것만 사면 나도 축구왕?????",
  "tags": ["4팀", "축123123구", "스트라이커"]
}


### 상품 수정
PATCH  {{localUrl}}/product/69fd29249c61df4ea4722bb0
Content-Type: application/json    

{
  "name": "레노버 노트북",
  "price": 100000,
  "description": "PATCH 테스트",
  "tags": ["#4팀", "#화이팅", "#김대영"]
}