@baseUrl = https://one3-sprint-mission-be-owah.onrender.com
@localUrl = http://localhost:3000


###상품 조회
GET {{localUrl}}/product?keyword=김대영


### 상품 목록 조회
GET {{localUrl}}/product


###
DELETE {{localUrl}}/product/69fc6147960a192a02277df5



### 상품 등록
POST {{localUrl}}/product
Content-Type: application/json

{
  "name": "데스크탑",
  "price": 1000000000,
  "description": "이것은 테스트 설명 입니다. 하하하하하하",
  "tags": ["#4팀", "#화123123이팅", "#김대영"]
}


### 상품 수정
PATCH  {{localUrl}}/product/69fd29249c61df4ea4722bb0
Content-Type: application/json    

{
  "name": "레노버 노트북",
  "price": 100000,
  "description": "PATCH 테스트",
  "tags": ["#4팀", "#화이팅", "#김대영"]
}