### 랜딩 페이지 
GET  http://localhost:3000

### 판다마켓 상품 조회
GET http://localhost:3000/items

### 판다마켓 상품 상세 조회
GET http://localhost:3000/items/
### 테스트 완료 

### 판다마켓 상품 등록
POST http://localhost:3000/items
Content-Type: application/json
### 테스트 완료
# {
#    "name": "macbookpro 원해요",
#   "description": "어쩌다보니 가성비 좋은 노트북",
#   "price": 2000000,
#   "tags": ["전자기기", "노트북"]
# }

### 판다마켓 상품 수정
PATCH http://localhost:3000/items/
Content-Type: application/json
///테스트완료

# {
# "name": "imac",
# "price": "5000000"
# }

### 판다마켓 상품 삭제
DELETE  http://localhost:3000/items/69fd7c64ccda368b4ad32702
###테스트 완료