@baseUrl = https://one3-sprint-mission-be-xody.onrender.com

### 랜딩 페이지 
GET  {{baseUrl}}

### 판다마켓 상품 조회
GET {{baseUrl}}/items

### 판다마켓 상품 상세 조회
GET {{baseUrl}}/items
### 테스트 완료 

### 판다마켓 상품 등록
POST {{baseUrl}}/items
Content-Type: application/json
### 테스트 완료
# {
#    "name": "macbookpro 원해요",
#   "description": "어쩌다보니 가성비 좋은 노트북",
#   "price": 2000000,
#   "tags": ["전자기기", "노트북"]
# }

### 판다마켓 상품 수정
PATCH {{baseUrl}}/items/
Content-Type: application/json
///테스트완료

# {
# "name": "imac",
# "price": 5000000
# }

### 판다마켓 상품 삭제
DELETE  {{baseUrl}}/items/69fd7c64ccda368b4ad32702
###테스트 완료