@baseUrl = http://localhost:3000

### MongoDB 기반 CRUD 테스트
### 
POST {{baseUrl}}/product
Content-Type: application/json

{
  "name": "맥북 네오",
  "description": "램 8GB, SSD 512GB 실버 모델입니다. 배터리 효율 90%!",
  "price": 2800000,
  "tags": ["노트북", "애플", "맥북", "전자기기"]
}
### 상세 조회 
GET {{baseUrl}}/product/69faf8a05c454e8a21dc712f

### 
PATCH {{baseUrl}}/product/69faf8a05c454e8a21dc712f
Content-Type: application/json

{
  "price": 99999999
}

###
DELETE {{baseUrl}}/product/69faf8a05c454e8a21dc712b

### 검색 
GET {{baseUrl}}/product?keyword=램&offset=0&limit=10

### postgres 테스트 (sprint mission 6) 
### Article 테스트 
### Article 목록
GET {{baseUrl}}/articles

### 
POST {{baseUrl}}/articles 
Content-Type: application/json

{
  "title":"테스트44",
  "content":"내용 내용 내용 내용 ....."
}

### 
POST {{baseUrl}}/articles/7/comments
Content-Type: application/json

{
  "content":"댓글하하하",
  "articleId": 1
}

### 댓글 목록
GET {{baseUrl}}/articles/7/comments

### cursor page1
GET {{baseUrl}}/articles/6/comments?limit=2

### cursor page2
GET {{baseUrl}}/articles/6/comments?limit=2&cursor=5

### 댓글  
PATCH {{baseUrl}}/articles/7/comments/11
Content-Type: application/json

{
  "content": "수정된 댓글", 
  "articleId": 7
}

### 댓글 삭제
DELETE {{baseUrl}}/articles/6/comments/4

### Article 단건 조회
GET {{baseUrl}}/articles/6

### Article 수정
PATCH {{baseUrl}}/articles/6
Content-Type: application/json

{
  "title": "수정된 제목",
  "content": "수정된 내용"
}

### Article 삭제
DELETE {{baseUrl}}/articles/6

### page 1
GET {{baseUrl}}/articles?page=1&limit=2

### page 2
GET {{baseUrl}}/articles?page=2&limit=2

### recent 정렬
GET {{baseUrl}}/articles?sort=recent

###
POST {{baseUrl}}/articles/1/comments
Content-Type: application/json

{
  "content": ""
}